/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low-poly_tree.glb 
Author: matulinekmaly (https://sketchfab.com/matulinekmaly)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-tree-644423562d8d4ed7aa7344b344159899
Title: Low-Poly Tree
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LowPolyTreeModel(props) {
  const { nodes, materials } = useGLTF("/models/low-poly_tree.glb");
  return (
    <group
      {...props}
      position={props.position}
      dispose={null}
      rotation={[0, 5, 0]}
    >
      <group scale={0.01}>
        {/* trunk */}
        <mesh
          geometry={nodes.Trunk_Trunk_0.geometry}
          material={materials.Trunk}
          position={[0, 0.3, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={12}
          castShadow
        />
        {/* foliage */}
        <mesh
          geometry={nodes.Leaves_Leaves_0.geometry}
          position={[11, 52, 11]}
          rotation={[-0.68, -0.37, 0.691]}
          scale={8}
          castShadow
        >
          {/* Swap #4CAF50 with any color hex code you like! */}
          <meshStandardMaterial
            color="#9EB045"
            roughness={0.6}
            flatShading={true}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/low-poly_tree.glb");
