/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_tree_3.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LowPolyTreeModel3(props) {
  const { nodes, materials } = useGLTF("/models/low_poly_tree_3.glb");
  return (
    <group {...props} dispose={null} rotation={[0, 6.4, 0]}>
      <mesh
        geometry={nodes.group2113862217.geometry}
        material={materials.mat9}
        scale={0.9}
        castShadow
      >
        <meshStandardMaterial
          color="#9EB045"
          roughness={0.6}
          flatShading={true}
        />
      </mesh>
      <mesh
        geometry={nodes.group1072121766.geometry}
        material={materials.mat20}
        castShadow
      />
      <mesh
        geometry={nodes.group50724889.geometry}
        material={materials.mat20}
        castShadow
      />
    </group>
  );
}

useGLTF.preload("/models/low_poly_tree_3.glb");
