/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_tree_2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LowPolyTreeModel2(props) {
  const { nodes, materials } = useGLTF("/models/low_poly_tree_2.glb");
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, 20, 0]}
      position={[0, 0.9, 0]}
    >
      <mesh
        geometry={nodes.group490856608.geometry}
        material={materials.mat9}
        scale={0.8}
        castShadow
      >
        <meshStandardMaterial
          color="#9EB045"
          roughness={0.6}
          flatShading={true}
        />
      </mesh>
      <mesh
        geometry={nodes.group378925630.geometry}
        material={materials.mat9}
        scale={0.8}
        castShadow
      >
        <meshStandardMaterial
          color="#9EB045"
          roughness={0.6}
          flatShading={true}
        />
      </mesh>
      {/* main trunk */}
      <mesh
        geometry={nodes.group280429710.geometry}
        material={materials.mat20}
        castShadow
      />
      <mesh
        geometry={nodes.group552992809.geometry}
        material={materials.mat20}
        castShadow
      />
      <mesh
        geometry={nodes.group936933673.geometry}
        material={materials.mat20}
        castShadow
      />
      <mesh
        geometry={nodes.group1058431921.geometry}
        material={materials.mat20}
        castShadow
      />
    </group>
  );
}

useGLTF.preload("/models/low_poly_tree_2.glb");
