/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rice_plant.glb --transform 
Files: public/models/rice_plant.glb [154.7KB] > D:\PR\automanexus\rice_plant-transformed.glb [22.04KB] (86%)
Author: dario scaramuzza (https://sketchfab.com/dariotolkien)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/rice-plant-68fd8a9b358144d895e3f7838e33e2a1
Title: Rice Plant
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rice_plant.glb --transform 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes } = useGLTF("/models/rice_plant-transformed.glb");

  return (
    <group {...props} dispose={null}>
      {/* 1. THE LEAVES & STALKS */}
      <mesh
        geometry={nodes.Object_3.geometry}
        position={[-11.419, -1.768, 10.841]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        {/* We inject a custom matte olive/sage green material */}
        <meshStandardMaterial color="#8a9463" roughness={0.8} metalness={0.1} />
      </mesh>

      {/* 2. THE RICE GRAINS */}
      <mesh
        geometry={nodes.Object_4.geometry}
        position={[-11.419, -1.768, 10.841]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        {/* We inject a custom soft golden/cream material */}
        <meshStandardMaterial color="#ded19c" roughness={0.9} metalness={0.0} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/rice_plant-transformed.glb");
